
cache:
    directories:
        - '$HOME/.composer/cache'

matrix:
    fast_finish: true
    include:
        -
            os: 'linux'
            dist: 'trusty'
            sudo: false
            language: 'php'
            php: '7.1'
#        -
#            os: 'osx'
#            language: 'generic'
#            env:
#                - 'BREW_PHP=php71'

before_install:
    - 'export COMPOSER_NO_INTERACTION=1'
    - 'export COMPOSER_DISABLE_XDEBUG_WARN=1'
    - "export RUBY_VERSION=$(bundle platform --ruby | awk '{print $2}')"
    - 'src-dev/scripts/travis/before_install.sh'

install:
    - 'rvm install "${RUBY_VERSION}"'
    - 'gem install bundler'
    - 'bundle check || bundle install'
    - 'composer install'

script:
    - './bin/robo lint'
    - './bin/robo test'

after_success:
    - 'bash <(curl -s https://codecov.io/bash)'

notifications:
    email: false
